credentials:
  usernames:
    stefan:
      email: s.emmoth@gmail.com
      name: Stefan
      password: $2b$12$n1Oq7a.tWIp1kDmkKq3AkuCv0mNNj5eWKdMJDIvWPiXqVXl/k2Tm2  # hashed: abc123
    
  
cookie:
  expiry_days: 30
  key: golf_tracker_secret_key_change_me
  name: golf_tracker_cookie

preauthorized:
  emails: []
